// SELLING_PARTNER_APP_CLIENT_ID=<YOUR_APP_CLIENT_ID>
// SELLING_PARTNER_APP_CLIENT_SECRET=<YOUR_APP_CLIENT_SECRET>
// AWS_ACCESS_KEY_ID=<YOUR_AWS_USER_ID>
// AWS_SECRET_ACCESS_KEY=<YOUR_AWS_USER_SECRET>
// AWS_SESSION_TOKEN=<YOUR_AWS_SESSION_TOKEN> // Only necessary when using temporary AWS STS security credentials
// AWS_SELLING_PARTNER_ROLE=<YOUR_AWS_SELLING_PARTNER_API_ROLE>